Add verification if file exist

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -56,6 +56,10 @@ jobs:
                     asset_name: gnome-shell-extension.zip
                     asset_content_type: application/zip
 
+            -   name: Verify extension.zip exists
+                run: |
+                    if [ -f "${{ github.workspace }}/src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip" ]; then echo "File exists"; else echo "File not found"; exit 1; fi
+
             -   name: Upload to GNOME Extensions
                 uses: fire-man-x/gnome-shell-extension-uploader@v1
                 with:
