Add storing artifact

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -50,11 +50,11 @@ jobs:
                     asset_name: gnome-shell-extension.zip
                     asset_content_type: application/zip
 
-            #-   name: Upload artifact
-            #    uses: actions/upload-artifact@v4
-            #    with:
-            #        name: ${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip
-            #        path: src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip
+            -   name: Upload artifact
+                uses: actions/upload-artifact@v4
+                with:
+                    name: shell-extension-artifact
+                    path: src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip
 
     upload_extension:
         runs-on: ubuntu-latest
@@ -65,13 +65,18 @@ jobs:
             -   name: Checkout code
                 uses: actions/checkout@v4
 
+            -   name: Download artifact
+                uses: actions/download-artifact@v4
+                with:
+                    name: shell-extension-artifact
+                    path: src/
+
             -   name: Verify extension.zip exists
-                run: |
-                    if [ -f "${{ github.workspace }}/src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip" ]; then echo "File exists"; else echo "File not found"; exit 1; fi
+                run: if [ -f "./src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip" ]; then echo "File exists"; else echo "File not found"; exit 1; fi
 
             -   name: Upload to GNOME Extensions
                 uses: fire-man-x/gnome-shell-extension-uploader@v1
                 with:
                     gnome_username: ${{ secrets.GNOME_USERNAME }}
                     gnome_password: ${{ secrets.GNOME_PASSWORD }}
-                    extension_zip_file: ${{ github.workspace }}/src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip
+                    extension_zip_file: ./src/${{ env.PROJECT_PACKAGE_NAME }}.shell-extension.zip
